# Generated by Django 4.0 on 2021-12-22 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
