# Generated by Django 4.0 on 2022-01-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_site', '0002_rename_users_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=1000)),
                ('img', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('record_date', models.DateTimeField()),
                ('picked', models.CharField(max_length=50)),
            ],
        ),
    ]
