# Generated by Django 4.0 on 2022-01-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_site', '0003_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='record_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
