# Generated by Django 4.0 on 2022-01-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_site', '0009_news_img_url_alter_news_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img_url',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
