# Generated by Django 4.0 on 2022-01-11 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_site', '0010_alter_news_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='img_url',
        ),
    ]
