# Generated by Django 4.0 on 2022-01-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_site', '0011_remove_news_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='./static/upload_images/'),
        ),
    ]
