# Generated by Django 4.0 on 2022-01-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_site', '0012_alter_news_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Safe_time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='upload_images'),
        ),
    ]
