# Generated by Django 4.0 on 2022-01-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_site', '0013_safe_time_alter_news_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delta_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Safe_time',
        ),
    ]
