# Generated by Django 4.0 on 2022-01-26 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first_site', '0015_delta_time_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='content',
            new_name='content_en',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='short_text',
            new_name='short_text_en',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='titel',
            new_name='titel_en',
        ),
        migrations.AddField(
            model_name='news',
            name='content_hu',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='short_text_hu',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='titel_hu',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
