# Generated by Django 4.0 on 2022-01-26 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_site', '0016_rename_content_news_content_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='content_en',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='short_text_en',
            new_name='short_text',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='titel_en',
            new_name='titel',
        ),
        migrations.RemoveField(
            model_name='news',
            name='content_hu',
        ),
        migrations.RemoveField(
            model_name='news',
            name='short_text_hu',
        ),
        migrations.RemoveField(
            model_name='news',
            name='titel_hu',
        ),
    ]
