# Generated by Django 4.0 on 2022-01-26 22:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('first_site', '0018_rename_content_news_content_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content_en',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_hu',
            field=tinymce.models.HTMLField(),
        ),
    ]
