# Generated by Django 4.0 on 2022-01-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_site', '0019_alter_news_content_en_alter_news_content_hu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=5)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=3)),
                ('absolute', models.DecimalField(decimal_places=2, max_digits=3)),
                ('record_date', models.DateTimeField(auto_now_add=True)),
                ('picked', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel_hu', models.CharField(max_length=50)),
                ('titel_en', models.CharField(max_length=50)),
                ('img_hu', models.ImageField(blank=True, null=True, upload_to='upload_images')),
                ('img_en', models.ImageField(blank=True, null=True, upload_to='upload_images')),
                ('record_date', models.DateTimeField(auto_now_add=True)),
                ('picked', models.CharField(max_length=50)),
            ],
        ),
    ]
