# Generated by Django 4.0 on 2022-02-01 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_site', '0020_product_value_slide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
