# Generated by Django 4.0 on 2022-02-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_site', '0021_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='record_date',
        ),
        migrations.AlterField(
            model_name='product_value',
            name='absolute',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='product_value',
            name='percentage',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='product_value',
            name='value',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
