# Generated by Django 4.0 on 2022-02-01 22:21

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('first_site', '0022_remove_slide_record_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel_hu', models.CharField(max_length=50)),
                ('short_text_hu', models.CharField(max_length=500)),
                ('content_hu', tinymce.models.HTMLField()),
                ('titel_en', models.CharField(max_length=50)),
                ('short_text_en', models.CharField(max_length=500)),
                ('content_en', tinymce.models.HTMLField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='upload_images')),
                ('file_titel_hu', models.CharField(max_length=50)),
                ('file_titel_en', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='upload_files')),
                ('record_date', models.DateTimeField(auto_now_add=True)),
                ('picked', models.CharField(max_length=50)),
            ],
        ),
    ]
