# Generated by Django 4.0 on 2022-02-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_site', '0023_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='type',
            field=models.CharField(blank=True, default='ann', max_length=50),
        ),
        migrations.AddField(
            model_name='news',
            name='type',
            field=models.CharField(blank=True, default='news', max_length=50),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='file',
            field=models.FileField(blank=True, upload_to='upload_files'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='file_titel_en',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='file_titel_hu',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
