# Generated by Django 4.0 on 2022-02-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_site', '0024_announcement_type_news_type_alter_announcement_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='type',
            field=models.CharField(default='ann', max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.CharField(default='news', max_length=50),
        ),
    ]
