# Generated by Django 4.0 on 2022-02-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_site', '0026_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='department',
            field=models.CharField(choices=[('it', 'IT'), ('hr', 'HR'), ('penzugy', 'PENZUGY')], default='EGYÉB', max_length=15),
        ),
    ]
