# Generated by Django 4.0 on 2022-02-13 16:43

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('first_site', '0029_document_file_document_file_titel_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel_hu', models.CharField(max_length=50)),
                ('titel_en', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('place', models.CharField(max_length=250)),
                ('description_hu', tinymce.models.HTMLField()),
                ('description_en', tinymce.models.HTMLField()),
                ('record_date', models.DateTimeField(auto_now_add=True)),
                ('picked', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='upload_docu'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_titel_en',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_titel_hu',
            field=models.CharField(max_length=50),
        ),
    ]
