# Generated by Django 4.0 on 2022-03-01 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_site', '0030_event_alter_announcement_file_titel_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='description_en',
            new_name='content_en',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='description_hu',
            new_name='content_hu',
        ),
    ]
