# Generated by Django 4.0 on 2022-03-01 21:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first_site', '0031_rename_description_en_event_content_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short_text_en',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='short_text_hu',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
