# Generated by Django 4.0 on 2022-03-01 21:18

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('first_site', '0032_event_short_text_en_event_short_text_hu'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.CharField(default='event', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='upload_files'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='file_titel_en',
            field=models.CharField(blank=True, help_text='Megadás kötelező, ha feltölt file-t / This is required when uploading a file', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='file_titel_hu',
            field=models.CharField(blank=True, help_text='Megadás kötelező, ha feltölt file-t / This is required when uploading a file', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='type',
            field=models.CharField(default='ann', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_titel_en',
            field=models.CharField(help_text='Megadás kötelező, ha feltölt file-t / This is required when uploading a file', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_titel_hu',
            field=models.CharField(help_text='Megadás kötelező, ha feltölt file-t / This is required when uploading a file', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='content_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='content_hu',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='type',
            field=models.CharField(default='news', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='slide',
            name='img_en',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='upload_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slide',
            name='img_hu',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='upload_images'),
            preserve_default=False,
        ),
    ]
