# Generated by Django 4.0 on 2022-03-01 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_site', '0033_event_type_alter_announcement_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='upload_images'),
        ),
    ]
